name: flutter_tmbd
description: A multi-platform Flutter client for The Movie Database (TMDB)
publish_to: "none"

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # --- HTTP Ð¸ API ---
  dio: ^5.7.0
  flutter_dotenv: ^6.0.0

  go_router: ^16.3.0

  flutter_riverpod: ^2.5.1

  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

  flutter_staggered_grid_view: ^0.7.0
  cached_network_image: ^3.3.1

  animations: ^2.0.11
  youtube_player_iframe: ^5.2.2
  url_launcher: ^6.3.0
  webview_flutter: ^4.8.0
  webview_flutter_android: ^4.10.5
  http: ^1.5.0

dependency_overrides:
  webview_flutter_wkwebview: 3.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  freezed: ^3.2.3
  json_serializable: ^6.9.0
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
